EDJ_debug = true;
private _laptopClass = ["Land_Laptop_unfolded_F", "Land_Laptop_03_black_F_AE3"] select isClass (configFile >> "CfgVehicles" >> "Land_Laptop_03_black_F_AE3");
edjLaptop = createVehicle [_laptopClass, [4000,4002,0], [], 0, "CAN_COLLIDE"];
edjOrdinaryLaptop = createVehicle [_laptopClass, [4003,4002,0], [], 0, "CAN_COLLIDE"];
edjPA = createVehicle ["Land_Loudspeakers_F", [4000,4010,0], [], 0, "CAN_COLLIDE"];
publicVariable "edjLaptop";
publicVariable "edjOrdinaryLaptop";
publicVariable "edjPA";
private _logicGroup = createGroup sideLogic;
private _workstationModule = _logicGroup createUnit ["Logic", [4000,4003,0], [], 0, "NONE"];
_workstationModule synchronizeObjectsAdd [edjLaptop];
[_workstationModule, [edjLaptop], true] call EDJ_fnc_moduleWorkstation;
diag_log format ["[EDJ TEST] workstation configured=%1 ordinary excluded=%2", edjLaptop getVariable ["EDJ_isWorkstation", false], !(edjOrdinaryLaptop getVariable ["EDJ_isWorkstation", false])];
private _ok = ["main", edjLaptop, edjPA, "groove", "carpinchos", []] call EDJ_fnc_registerStage;
diag_log format ["[EDJ TEST] stage registration=%1 dedicated=%2", _ok, isDedicated];
private _duplicate = ["main", edjLaptop, edjPA] call EDJ_fnc_registerStage;
diag_log format ["[EDJ TEST] duplicate rejected=%1", !_duplicate];
private _missing = ["missing", objNull, edjPA] call EDJ_fnc_registerStage;
diag_log format ["[EDJ TEST] null workstation rejected=%1", !_missing];
diag_log format ["[EDJ TEST] patches=%1", ["A3_Characters_F", "A3_Characters_F_BLUFOR", "cba_common", "cba_events", "ace_main", "ae3_desktop", "live_radio_manager"] apply {[_x, isClass (configFile >> "CfgPatches" >> _x)]}];
diag_log format ["[EDJ TEST] soldier addons=%1", configSourceAddonList (configFile >> "CfgVehicles" >> "B_Soldier_F")];
private _revision = (EDJ_stages get "main") get "revision";
["main", [["masterVolume", 1]], "test_noop"] call EDJ_fnc_commitStage;
diag_log format ["[EDJ TEST] no-op revision stable=%1", (EDJ_stages get "main") get "revision" == _revision];
