if (!hasInterface) exitWith {};
[] spawn {
    private _deadline = diag_tickTime + 45;
    waitUntil {sleep 0.1; (missionNamespace getVariable ["EDJ_audioReady", false] && {"main" in EDJ_clientStages}) || {diag_tickTime > _deadline}};
    if (!("main" in EDJ_clientStages)) exitWith {diag_log "[EDJ M1] FAIL stage_timeout"; endMission "END1";};
    player allowDamage false;
    player setPosATL [4000,4000,0];
    private _check = {params ["_name", "_ok"]; diag_log format ["[EDJ M1] %1=%2", _name, ["FAIL", "PASS"] select _ok];};
    [edjLaptop] call AE3_desktop_fnc_desktop_openWeb;
    sleep 1;
    [edjLaptop, "", createHashMap, "", "edj_open_event_dj"] call EDJ_fnc_ae3OpenWebApp;
    sleep 2;
    private _windows = (uiNamespace getVariable ["AE3_desktop_session", createHashMap]) getOrDefault ["windows", createHashMap];
    private _ids = keys _windows select {((_windows get _x) get "app") == "EDJ_EventDJ"};
    if (_ids isEqualTo []) exitWith {diag_log "[EDJ M1] FAIL workstation_window"; endMission "END1";};
    private _body = uiNamespace getVariable ["EDJ_ae3_" + str (_ids select 0), controlNull];
    private _controls = _body getVariable ["EDJ_namedControls", createHashMap];
    if (count _controls == 0) exitWith {diag_log "[EDJ M1] FAIL workstation_controls"; endMission "END1";};
    ["ae3_workstation", true] call _check;
    (_controls get "claim") call EDJ_fnc_control;
    sleep 0.5;
    ["claim_through_controller", (EDJ_clientStages get "main") get "operator" == player] call _check;
    _body setVariable ["EDJ_selectedTrack", "edj_miniaudio_acceptance"];
    (_controls get "loadA") call EDJ_fnc_control;
    sleep 0.5;
    ["registered_track_loaded", (EDJ_clientStages get "main") get "audioSource" == "edj_miniaudio_acceptance"] call _check;
    for "_cycle" from 1 to 3 do {
        (_controls get "playA") call EDJ_fnc_control;
        sleep 2;
        private _status = "edj_miniaudio" callExtension ["playback_status", ["main"]];
        [format ["play_%1", _cycle], (_status select 0) == "playing"] call _check;
        private _meter = ("edj_miniaudio" callExtension ["meter", []]) select 0;
        diag_log format ["[EDJ M1] meter_%1=%2", _cycle, _meter];
        private _parts = _meter splitString ":";
        [format ["device_pcm_%1", _cycle], count _parts >= 5 && {parseNumber (_parts select 2) > 0} && {(_parts select 4) == "1"} && {!((_parts select 1) in ["Null", "null", "no_device"])}] call _check;
        private _before = (("edj_miniaudio" callExtension ["debug_source", ["main"]]) select 0) splitString ":";
        (_controls get "volume") sliderSetPosition 0.25;
        _body setVariable ["EDJ_pendingVolume", [0.25, diag_tickTime - 1]];
        sleep 1;
        private _after = (("edj_miniaudio" callExtension ["debug_source", ["main"]]) select 0) splitString ":";
        diag_log format ["[EDJ M1] live_gain_%1=%2 -> %3", _cycle, _before, _after];
        [format ["live_gain_no_restart_%1", _cycle], count _before == 4 && {count _after == 4} && {parseNumber (_after select 1) == 0.5} && {parseNumber (_after select 2) > parseNumber (_before select 2)} && {(_after select 3) == (_before select 3)}] call _check;
        (_controls get "stopA") call EDJ_fnc_control;
        sleep 0.5;
        [format ["stop_%1", _cycle], (("edj_miniaudio" callExtension ["playback_status", ["main"]]) select 0) == "missing"] call _check;
        (_controls get "volume") sliderSetPosition 1;
        _body setVariable ["EDJ_pendingVolume", [1, diag_tickTime - 1]];
        sleep 1;
    };
    (_controls get "release") call EDJ_fnc_control;
    "edj_miniaudio" callExtension ["shutdown", []];
    diag_log "[EDJ M1] COMPLETE - device PCM is not human listening confirmation; M2 remains gated";
    sleep 1;
    endMission "END1";
};
