if (!hasInterface) exitWith {};
[] spawn {
    private _deadline = diag_tickTime + 45;
    waitUntil {sleep 0.1; (missionNamespace getVariable ["EDJ_audioReady", false] && {"main" in EDJ_clientStages}) || {diag_tickTime > _deadline}};
    if (!("main" in EDJ_clientStages)) exitWith {diag_log "[EDJ ARRAYS] FAIL stage_timeout"; endMission "END1";};
    player allowDamage false; player setPosATL [4000,4000,0];
    private _check = {params ["_name", "_ok"]; diag_log format ["[EDJ ARRAYS] %1=%2", _name, ["FAIL", "PASS"] select _ok];};
    private _invoke = {params ["_op", ["_args", ["main"]]]; ("edj_miniaudio" callExtension [_op, _args]) select 0};
    private _position = {parseNumber ((["position"] call _invoke) splitString ":" select 1)};
    [edjLaptop] call AE3_desktop_fnc_desktop_openWeb; sleep 1;
    [edjLaptop, "", createHashMap, "", "edj_open_event_dj"] call EDJ_fnc_ae3OpenWebApp; sleep 2;
    private _windows = (uiNamespace getVariable ["AE3_desktop_session", createHashMap]) getOrDefault ["windows", createHashMap];
    private _ids = keys _windows select {((_windows get _x) get "app") == "EDJ_EventDJ"};
    if (_ids isEqualTo []) exitWith {diag_log "[EDJ ARRAYS] FAIL workstation"; endMission "END1";};
    private _body = uiNamespace getVariable ["EDJ_ae3_" + str (_ids select 0), controlNull];
    private _controls = _body getVariable ["EDJ_namedControls", createHashMap];
    (_controls get "claim") call EDJ_fnc_control; sleep 0.5;
    if ((loadFile "human_test.txt") find "SingleArray" >= 0) exitWith {
        titleText ["TEST 1: ONE FOUR-CABINET ARRAY\nListen for one continuous tone, then silence after STOP.", "PLAIN", 0.2];
        (_controls get "playA") call EDJ_fnc_control;
        sleep 8;
        (_controls get "stopA") call EDJ_fnc_control;
        titleText ["TEST 1: STOP\nThe tone should now be silent. Reply PASS, FAIL, BLOCKED or SKIP.", "PLAIN", 0.2];
        sleep 4;
        endMission "END1";
    };
    if ((loadFile "human_test.txt") find "Dual" >= 0) exitWith {
        private _volumeTest = (loadFile "human_test.txt") find "DualVolume" >= 0;
        private _pauseTest = (loadFile "human_test.txt") find "DualPause" >= 0;
        private _seekTest = (loadFile "human_test.txt") find "DualSeek" >= 0;
        private _completionTest = (loadFile "human_test.txt") find "DualCompletion" >= 0;
        private _directionTest = (loadFile "human_test.txt") find "DualDirection" >= 0;
        private _rangeTest = (loadFile "human_test.txt") find "DualRange" >= 0;
        private _listenerTest = (loadFile "human_test.txt") find "DualListener" >= 0;
        private _moveListenerTest = (loadFile "human_test.txt") find "DualMoveListener" >= 0;
        private _moveArraysTest = (loadFile "human_test.txt") find "DualMoveArrays" >= 0;
        private _cueTest = (loadFile "human_test.txt") find "DualCue" >= 0;
        private _deleteTest = (loadFile "human_test.txt") find "DualDelete" >= 0;
        private _testNumber = if (_listenerTest) then {9} else {if (_rangeTest) then {8} else {if (_directionTest) then {7} else {if (_completionTest) then {6} else {if (_seekTest) then {5} else {if (_pauseTest) then {4} else {[2,3] select _volumeTest}}}}}};
        { _x setPosASL ((getPosASL _x) vectorAdd [-8,0,0]); } forEach edjCabinets;
        private _g = createGroup sideLogic;
        private _right = _g createUnit ["EDJ_Module_SpeakerArray", [4008,4010,0], [], 0, "NONE"];
        _right setDir 180;
        private _cabinets = [];
        {_cabinets pushBack createVehicle ["Land_Loudspeakers_F", [4008+_x,4010,0], [], 0, "CAN_COLLIDE"];} forEach [-3,-1,1,3];
        _right synchronizeObjectsAdd _cabinets;
        edjMainPA synchronizeObjectsAdd [_right];
        ["main", [["speakerArrays", [[edjArray, edjCabinets], [_right, _cabinets]]]], "test_dual_array_setup"] call EDJ_fnc_commitStage;
        player setDir 0;
        sleep 0.5;
        if (_moveListenerTest) then {_testNumber = 10;};
        if (_moveArraysTest) then {_testNumber = 11;};
        if (_cueTest) then {_testNumber = 12;};
        if (_deleteTest) then {_testNumber = 13;};
        titleText [format ["TEST %1: LEFT / RIGHT ARRAYS\nBoth four-cabinet arrays play together. Follow the on-screen steps.", _testNumber], "PLAIN", 0.2];
        (_controls get "playA") call EDJ_fnc_control;
        sleep 1;
        private _serial = (["debug_source"] call _invoke) splitString ":" select 3;
        ["human_two_emitters", ((["arrays"] call _invoke) splitString ":" select 1) == "2"] call _check;
        ["human_dual_pcm", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) > 0.001] call _check;
        if (_deleteTest) exitWith {
            // Remove the distant fallback so the final array really is the last source.
            deleteVehicle edjPA;
            titleText ["TEST 13: BOTH ARRAYS PLAYING\nThe test will remove the left array, then the right array. Do not press STOP.", "PLAIN", 0.2];
            sleep 2;
            deleteVehicle edjArray;
            {deleteVehicle _x;} forEach edjCabinets;
            titleText ["TEST 13: LEFT ARRAY REMOVED\nThe right array should keep playing without restarting.", "PLAIN", 0.2];
            sleep 2;
            ["human_delete_one_remaining", ((["arrays"] call _invoke) splitString ":" select 1) == "1"] call _check;
            ["human_delete_source_unchanged", ((["debug_source"] call _invoke) splitString ":" select 3) == _serial] call _check;
            ["human_delete_remaining_pcm", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) > 0.001] call _check;
            deleteVehicle _right;
            {deleteVehicle _x;} forEach _cabinets;
            titleText ["TEST 13: LAST ARRAY REMOVED\nAudio should stop automatically. The workstation should show stopped playback.", "PLAIN", 0.2];
            sleep 2;
            ["human_delete_last_source_cleaned", (["playback_status"] call _invoke) == "missing"] call _check;
            ["human_delete_stage_stopped", (EDJ_clientStages get "main") get "playback" == "stopped"] call _check;
            ["human_delete_last_silent", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) < 0.00001] call _check;
            sleep 2;
            ["human_delete_no_restart", (["playback_status"] call _invoke) == "missing"] call _check;
            diag_log "[EDJ ARRAYS] DELETE SCENARIO COMPLETE - human confirmation required";
            endMission "END1";
        };
        if (_cueTest) exitWith {
            ["main", "volume", 0] call EDJ_fnc_request;
            titleText ["TEST 12: MAIN OUTPUT MUTED\nBoth arrays should be silent. The main track keeps progressing.", "PLAIN", 0.2];
            sleep 1;
            ["human_cue_main_silent", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) < 0.00001] call _check;
            (_controls get "cueA") call EDJ_fnc_control;
            titleText ["TEST 12: DJ CUE ON\nYou should hear the preview despite the main output being muted.", "PLAIN", 0.2];
            sleep 2;
            ["human_cue_running", (["playback_status", ["cue:main"]] call _invoke) == "playing"] call _check;
            ["human_cue_audible_pcm", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) > 0.001] call _check;
            private _mainPosition = call _position;
            (_controls get "cueA") call EDJ_fnc_control;
            titleText ["TEST 12: DJ CUE OFF\nSilence should return. The main track should keep progressing.", "PLAIN", 0.2];
            sleep 1;
            ["human_cue_destroyed", (["playback_status", ["cue:main"]] call _invoke) == "missing"] call _check;
            ["human_cue_off_silent", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) < 0.00001] call _check;
            ["human_cue_main_continues", (call _position) > _mainPosition + 0.7] call _check;
            ["main", "volume", 1] call EDJ_fnc_request;
            titleText ["TEST 12: MAIN OUTPUT RESTORED\nBoth arrays should return at the ongoing track position, without restarting.", "PLAIN", 0.2];
            sleep 2;
            ["human_cue_main_source_unchanged", ((["debug_source"] call _invoke) splitString ":" select 3) == _serial] call _check;
            (_controls get "stopA") call EDJ_fnc_control;
            sleep 0.3;
            ["human_cue_final_cleanup", (["playback_status"] call _invoke) == "missing" && {(["playback_status", ["cue:main"]] call _invoke) == "missing"}] call _check;
            titleText ["TEST 12: STOP\nReply PASS, FAIL, BLOCKED or SKIP. Other-client cue isolation is tested separately.", "PLAIN", 0.2];
            sleep 3;
            diag_log "[EDJ ARRAYS] CUE SCENARIO COMPLETE - human confirmation required";
            endMission "END1";
        };
        if (_moveArraysTest) exitWith {
            titleText ["TEST 11: MOVING ARRAYS\nYou stay still. Both arrays move right, then left, then return. Listen for smooth spatial changes without gaps or restarts.", "PLAIN", 0.2];
            private _allCabinets = edjCabinets + _cabinets;
            private _origins = _allCabinets apply {getPosASL _x};
            private _revision = (EDJ_clientStages get "main") get "revision";
            private _start = diag_tickTime;
            private _elapsed = 0;
            while {_elapsed < 6} do {
                _elapsed = diag_tickTime - _start;
                private _dx = 18 * sin (_elapsed * 60);
                {_x setPosASL ((_origins select _forEachIndex) vectorAdd [_dx,0,0]);} forEach _allCabinets;
                sleep 0.05;
            };
            {_x setPosASL (_origins select _forEachIndex);} forEach _allCabinets;
            sleep 0.3;
            ["human_move_arrays_stable_source", ((["debug_source"] call _invoke) splitString ":" select 3) == _serial] call _check;
            ["human_move_arrays_playing", (["playback_status"] call _invoke) == "playing"] call _check;
            ["human_move_arrays_count", ((["arrays"] call _invoke) splitString ":" select 1) == "2"] call _check;
            ["human_move_arrays_no_revisions", ((EDJ_clientStages get "main") get "revision") == _revision] call _check;
            (_controls get "stopA") call EDJ_fnc_control;
            sleep 0.3;
            ["human_move_arrays_stop", (["playback_status"] call _invoke) == "missing"] call _check;
            titleText ["TEST 11: STOP\nBoth arrays should be silent. Reply PASS, FAIL, BLOCKED or SKIP.", "PLAIN", 0.2];
            sleep 3;
            diag_log "[EDJ ARRAYS] MOVING ARRAYS SCENARIO COMPLETE - human confirmation required";
            endMission "END1";
        };
        if (_moveListenerTest) exitWith {
            titleText ["TEST 10: MOVING LISTENER\nYour character moves right, then left, then back to the workstation. Listen for smooth spatial changes without gaps or restarts.", "PLAIN", 0.2];
            private _origin = getPosASL player;
            private _start = diag_tickTime;
            private _elapsed = 0;
            while {_elapsed < 6} do {
                _elapsed = diag_tickTime - _start;
                private _dx = 18 * sin (_elapsed * 60);
                player setPosASL (_origin vectorAdd [_dx,0,0]);
                player setDir 0;
                sleep 0.05;
            };
            player setPosASL _origin;
            player setDir 0;
            ["human_move_listener_stable_source", ((["debug_source"] call _invoke) splitString ":" select 3) == _serial] call _check;
            ["human_move_listener_playing", (["playback_status"] call _invoke) == "playing"] call _check;
            ["human_move_listener_both_arrays", ((["arrays"] call _invoke) splitString ":" select 1) == "2"] call _check;
            // Moving away correctly releases operator ownership. Reclaim locally
            // at the workstation before testing STOP through its normal control.
            (_controls get "claim") call EDJ_fnc_control;
            sleep 0.5;
            (_controls get "stopA") call EDJ_fnc_control;
            sleep 0.3;
            ["human_move_listener_stop", (["playback_status"] call _invoke) == "missing"] call _check;
            titleText ["TEST 10: STOP\nBoth arrays should be silent. Reply PASS, FAIL, BLOCKED or SKIP.", "PLAIN", 0.2];
            sleep 3;
            diag_log "[EDJ ARRAYS] MOVING LISTENER SCENARIO COMPLETE - human confirmation required";
            endMission "END1";
        };
        if (_listenerTest) exitWith {
            titleText ["TEST 9: FACING THE ARRAYS\nUse stereo headphones or speakers. Sound should be roughly balanced left/right.", "PLAIN", 0.2];
            sleep 2;
            player setDir 90;
            titleText ["TEST 9: TURNED RIGHT\nThe fixed arrays are now to your LEFT. Sound should favor your LEFT ear.", "PLAIN", 0.2];
            sleep 2;
            ["human_listener_facing_east", (eyeDirection player select 0) > 0.8] call _check;
            player setDir 270;
            titleText ["TEST 9: TURNED LEFT\nThe fixed arrays are now to your RIGHT. Sound should favor your RIGHT ear.", "PLAIN", 0.2];
            sleep 2;
            ["human_listener_facing_west", (eyeDirection player select 0) < -0.8] call _check;
            player setDir 0;
            titleText ["TEST 9: FACING THE ARRAYS AGAIN\nSound should return to roughly balanced left/right without restarting.", "PLAIN", 0.2];
            sleep 1;
            ["human_listener_stable_source", ((["debug_source"] call _invoke) splitString ":" select 3) == _serial] call _check;
            ["human_listener_pcm", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) > 0.001] call _check;
            (_controls get "stopA") call EDJ_fnc_control;
            sleep 0.3;
            ["human_listener_stop", (["playback_status"] call _invoke) == "missing"] call _check;
            titleText ["TEST 9: STOP\nReply PASS, FAIL, BLOCKED or SKIP. Mono output cannot verify stereo positioning.", "PLAIN", 0.2];
            sleep 3;
            diag_log "[EDJ ARRAYS] LISTENER SCENARIO COMPLETE - human stereo confirmation required";
            endMission "END1";
        };
        if (_rangeTest) exitWith {
            private _allCabinets = edjCabinets + _cabinets;
            private _move = {params ["_dy"]; {_x setPosASL ((getPosASL _x) vectorAdd [0,_dy,0]);} forEach _allCabinets;};
            private _revision = (EDJ_clientStages get "main") get "revision";
            titleText ["TEST 8: ARRAYS NEARBY\nListen to the initial volume. The arrays will move away and return automatically.", "PLAIN", 0.2];
            sleep 2;
            private _near = parseNumber ((["meter", []] call _invoke) splitString ":" select 2);
            [60] call _move;
            titleText ["TEST 8: ARRAYS FARTHER AWAY\nThe tone should become quieter as the arrays move to about 70 metres.", "PLAIN", 0.2];
            sleep 2;
            private _far = parseNumber ((["meter", []] call _invoke) splitString ":" select 2);
            ["human_range_far_quieter", _near > 0.001 && {_far > 0.00001} && {_far < _near * 0.6}] call _check;
            [60] call _move;
            titleText ["TEST 8: ARRAYS OUTSIDE RANGE\nBoth arrays are beyond 100 metres and should become silent.", "PLAIN", 0.2];
            sleep 2;
            ["human_range_outside_silent", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) < 0.00001] call _check;
            [-120] call _move;
            titleText ["TEST 8: ARRAYS RETURNED\nThe tone should return without starting the track again.", "PLAIN", 0.2];
            sleep 1.5;
            ["human_range_return_audible", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) > _near * 0.7] call _check;
            ["human_range_stable_source", ((["debug_source"] call _invoke) splitString ":" select 3) == _serial] call _check;
            ["human_range_no_revisions", ((EDJ_clientStages get "main") get "revision") == _revision] call _check;
            (_controls get "stopA") call EDJ_fnc_control;
            sleep 0.3;
            ["human_range_stop", (["playback_status"] call _invoke) == "missing"] call _check;
            titleText ["TEST 8: STOP\nBoth arrays should now be silent. Reply PASS, FAIL, BLOCKED or SKIP.", "PLAIN", 0.2];
            sleep 3;
            diag_log "[EDJ ARRAYS] RANGE SCENARIO COMPLETE - human confirmation required";
            endMission "END1";
        };
        if (_directionTest) exitWith {
            titleText ["TEST 7: ARRAYS FACING YOU\nListen to the initial volume. The cabinets stay in place; the array modules define their facing.", "PLAIN", 0.2];
            sleep 2;
            private _front = parseNumber ((["meter", []] call _invoke) splitString ":" select 2);
            private _revision = (EDJ_clientStages get "main") get "revision";
            edjArray setDir 0; _right setDir 0;
            titleText ["TEST 7: ARRAYS FACING AWAY\nThe tone should become substantially quieter, without restarting.", "PLAIN", 0.2];
            sleep 2;
            private _rear = parseNumber ((["meter", []] call _invoke) splitString ":" select 2);
            ["human_direction_rear_attenuated", _front > 0.001 && {_rear < _front * 0.3}] call _check;
            sleep 1;
            edjArray setDir 180; _right setDir 180;
            titleText ["TEST 7: ARRAYS FACING YOU AGAIN\nThe original volume should return. Playback should remain continuous.", "PLAIN", 0.2];
            sleep 2;
            private _returned = parseNumber ((["meter", []] call _invoke) splitString ":" select 2);
            ["human_direction_front_restored", _returned > _rear * 3] call _check;
            ["human_direction_stable_source", ((["debug_source"] call _invoke) splitString ":" select 3) == _serial] call _check;
            ["human_direction_no_revisions", ((EDJ_clientStages get "main") get "revision") == _revision] call _check;
            (_controls get "stopA") call EDJ_fnc_control;
            sleep 0.3;
            ["human_direction_stop", (["playback_status"] call _invoke) == "missing"] call _check;
            titleText ["TEST 7: STOP\nBoth arrays should now be silent. Reply PASS, FAIL, BLOCKED or SKIP.", "PLAIN", 0.2];
            sleep 3;
            diag_log "[EDJ ARRAYS] DIRECTION SCENARIO COMPLETE - human confirmation required";
            endMission "END1";
        };
        if (_completionTest) exitWith {
            titleText ["TEST 6: NATURAL COMPLETION\nLet the 12-second track finish. Do not press STOP. Both arrays should fall silent automatically.", "PLAIN", 0.2];
            sleep 12.5;
            private _stage = EDJ_clientStages get "main";
            private _deck = createHashMapFromArray ((_stage get "decks") select 0);
            ["human_completion_stage_stopped", _stage get "playback" == "stopped"] call _check;
            ["human_completion_deck_stopped", _deck get "playbackState" == "STOPPED"] call _check;
            ["human_completion_source_destroyed", (["playback_status"] call _invoke) == "missing"] call _check;
            ["human_completion_silent", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) < 0.00001] call _check;
            titleText ["TEST 6: TRACK FINISHED\nBoth arrays should remain silent and the workstation should show stopped playback.", "PLAIN", 0.2];
            sleep 3;
            ["human_completion_no_restart", (["playback_status"] call _invoke) == "missing"] call _check;
            diag_log "[EDJ ARRAYS] NATURAL COMPLETION SCENARIO COMPLETE - human confirmation required";
            endMission "END1";
        };
        if (_volumeTest) then {
            sleep 1;
            ["main", "volume", 0.25] call EDJ_fnc_request;
            titleText ["TEST 3: BOTH ARRAYS AT 25%\nThe tone should become quieter without restarting.", "PLAIN", 0.2];
            sleep 2;
            ["main", "volume", 1] call EDJ_fnc_request;
            titleText ["TEST 3: BOTH ARRAYS AT 100%\nThe tone should become louder without restarting.", "PLAIN", 0.2];
            sleep 2;
            ["main", "volume", 0] call EDJ_fnc_request;
            titleText ["TEST 3: BOTH ARRAYS AT 0%\nBoth should be silent while the track continues.", "PLAIN", 0.2];
            sleep 2;
            ["human_dual_muted", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) < 0.00001] call _check;
        } else {
            if (_pauseTest) then {
                sleep 2;
                (_controls get "pauseA") call EDJ_fnc_control;
                titleText ["TEST 4: PAUSED\nBoth arrays should be silent and progress should stop.", "PLAIN", 0.2];
                sleep 0.4;
                private _pausedAt = call _position;
                sleep 2;
                ["human_dual_paused_cursor", abs ((call _position) - _pausedAt) < 0.05] call _check;
                ["human_dual_paused_silent", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) < 0.00001] call _check;
                (_controls get "pauseA") call EDJ_fnc_control;
                titleText ["TEST 4: RESUMED\nBoth arrays should resume together. Progress should continue from the paused position.", "PLAIN", 0.2];
                sleep 1;
                ["human_dual_resumed_position", abs ((call _position) - _pausedAt - 1) < 0.3] call _check;
                ["human_dual_resumed_pcm", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) > 0.001] call _check;
                sleep 2;
            } else {
                if (_seekTest) then {
                    sleep 1;
                    ["main", "deckSeek", ["A", 6]] call EDJ_fnc_request;
                    titleText ["TEST 5: SEEK TO 6 SECONDS\nProgress should jump forward. Both arrays should continue together.", "PLAIN", 0.2];
                    sleep 0.5;
                    ["human_seek_playing_position", abs ((call _position) - 6.5) < 0.3] call _check;
                    sleep 1;
                    (_controls get "pauseA") call EDJ_fnc_control;
                    sleep 0.5;
                    ["main", "deckSeek", ["A", 2]] call EDJ_fnc_request;
                    titleText ["TEST 5: PAUSED SEEK TO 2 SECONDS\nProgress should move back to 2 seconds. Both arrays must stay silent.", "PLAIN", 0.2];
                    sleep 0.5;
                    ["human_seek_paused_position", abs ((call _position) - 2) < 0.05] call _check;
                    ["human_seek_paused_silent", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) < 0.00001] call _check;
                    sleep 1.5;
                    (_controls get "pauseA") call EDJ_fnc_control;
                    titleText ["TEST 5: RESUME FROM 2 SECONDS\nBoth arrays should resume together from the new position.", "PLAIN", 0.2];
                    sleep 1;
                    ["human_seek_resume_position", abs ((call _position) - 3) < 0.3] call _check;
                    ["human_seek_resume_pcm", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) > 0.001] call _check;
                    sleep 2;
                } else {sleep 7;};
            };
        };
        ["human_dual_stable_source", ((["debug_source"] call _invoke) splitString ":" select 3) == _serial] call _check;
        (_controls get "stopA") call EDJ_fnc_control;
        sleep 0.3;
        ["human_dual_stop", (["playback_status"] call _invoke) == "missing"] call _check;
        titleText [format ["TEST %1: STOP\nBoth arrays should now be silent. Reply PASS, FAIL, BLOCKED or SKIP.", _testNumber], "PLAIN", 0.2];
        sleep 4;
        diag_log "[EDJ ARRAYS] DUAL HUMAN SCENARIO COMPLETE - listening confirmation required";
        endMission "END1";
    };
    (_controls get "playA") call EDJ_fnc_control; sleep 2;
    private _serial = (["debug_source"] call _invoke) splitString ":" select 3;
    private _arrays = (["arrays"] call _invoke) splitString ":";
    diag_log format ["[EDJ ARRAYS] geometry=%1", _arrays];
    ["four_cabinets_one_emitter", count _arrays == 10 && {(_arrays select 1) == "1"} && {abs (parseNumber (_arrays select 2) - 4000) < 0.2}] call _check;
    ["array_pcm", parseNumber ((["meter", []] call _invoke) splitString ":" select 2) > 0.001] call _check;
    ["duration", abs (parseNumber ((["duration"] call _invoke) splitString ":" select 1) - 12) < 0.05] call _check;
    ("pauseA" call { _controls get _this }) call EDJ_fnc_control; sleep 0.5;
    private _p = call _position; sleep 0.7;
    ["pause_cursor", abs ((call _position) - _p) < 0.05 && {(["playback_status"] call _invoke) == "paused"}] call _check;
    ["main", "deckSeek", ["A", 6]] call EDJ_fnc_request; sleep 0.5;
    ["seek_paused", abs ((call _position) - 6) < 0.05] call _check;
    ["main", "deckResume", "A"] call EDJ_fnc_request; sleep 0.7;
    ["resume_cursor", (call _position) > 6.3 && {(call _position) < 7.5}] call _check;
    ["main", "deckSeek", ["A", 2]] call EDJ_fnc_request; sleep 0.5;
    ["seek_playing", (call _position) > 2 && {(call _position) < 3}] call _check;
    ["controls_preserve_source", ((["debug_source"] call _invoke) splitString ":" select 3) == _serial] call _check;
    private _revision = (EDJ_clientStages get "main") get "revision";
    { _x setPosASL ((getPosASL _x) vectorAdd [5,0,0]); } forEach edjCabinets;
    edjArray setDir 270; sleep 0.3;
    _arrays = (["arrays"] call _invoke) splitString ":";
    ["moving_centroid", abs (parseNumber (_arrays select 2) - 4005) < 0.2] call _check;
    ["moving_direction", parseNumber (_arrays select 5) < -0.99] call _check;
    ["no_spatial_revisions", ((EDJ_clientStages get "main") get "revision") == _revision] call _check;
    ["main", "volume", 0.25] call EDJ_fnc_request; sleep 0.4;
    ["live_volume", ((["debug_source"] call _invoke) splitString ":" select 1) == "0.5"] call _check;
    ["main", "A"] call EDJ_fnc_audioCue; sleep 0.4;
    ["cue_independent", (["playback_status", ["cue:main"]] call _invoke) == "playing" && {((["debug_source"] call _invoke) splitString ":" select 3) == _serial}] call _check;
    ["main", "", "stop"] call EDJ_fnc_audioCue;
    ["main", "deckSeek", ["A", 11]] call EDJ_fnc_request; sleep 2.5;
    ["completion_server", (EDJ_clientStages get "main") get "playback" == "stopped"] call _check;
    ["completion_cleanup", (["playback_status"] call _invoke) == "missing"] call _check;
    for "_cycle" from 1 to 3 do {
        ["main", "deckPlay", "A"] call EDJ_fnc_request; sleep 2.1;
        [format ["repeat_play_%1", _cycle], (["playback_status"] call _invoke) == "playing"] call _check;
        ["main", "deckStop", "A"] call EDJ_fnc_request; sleep 0.4;
        [format ["repeat_stop_%1", _cycle], (["playback_status"] call _invoke) == "missing"] call _check;
    };
    private _g = createGroup sideLogic;
    private _right = _g createUnit ["EDJ_Module_SpeakerArray", [4010,4010,0], [], 0, "NONE"];
    _right setDir 180;
    private _rightCabinets = [];
    {_rightCabinets pushBack createVehicle ["Land_Loudspeakers_F", [4010+_x,4010,0], [], 0, "CAN_COLLIDE"];} forEach [-3,-1,1,3];
    _right synchronizeObjectsAdd _rightCabinets;
    ["main", [["speakerArrays", [[edjArray, edjCabinets], [_right, _rightCabinets]]]], "test_two_arrays"] call EDJ_fnc_commitStage;
    sleep 0.5;
    ["main", "deckPlay", "A"] call EDJ_fnc_request; sleep 1;
    ["left_right_two_emitters", ((["arrays"] call _invoke) splitString ":" select 1) == "2"] call _check;
    private _stage = EDJ_clientStages get "main";
    ["stop"] call _invoke; EDJ_audioInstances deleteAt "main";
    [_stage] call EDJ_fnc_audioApply; sleep 0.5;
    private _expected = (_stage get "startOffset") + serverTime - (_stage get "startServerTime");
    ["recreate_from_server_time", abs ((call _position) - _expected) < 0.3] call _check;
    ["recreate_all_arrays", ((["arrays"] call _invoke) splitString ":" select 1) == "2"] call _check;
    deleteVehicle _right; sleep 0.5;
    ["deleted_array_removed", ((["arrays"] call _invoke) splitString ":" select 1) == "1"] call _check;
    ["main", "deckStop", "A"] call EDJ_fnc_request; sleep 0.5;
    ["main", [["speakerArrays", []]], "test_fallback"] call EDJ_fnc_commitStage;
    edjPA setPosATL [4000,4010,0]; edjPA setDir 180;
    sleep 1;
    ["main", "deckPlay", "A"] call EDJ_fnc_request; sleep 1;
    _arrays = (["arrays"] call _invoke) splitString ":";
    ["physical_fallback", count _arrays == 10 && {abs (parseNumber (_arrays select 2) - 4000) < 0.2}] call _check;
    deleteVehicle edjPA; sleep 1.5;
    ["deleted_last_source_cleanup", (["playback_status"] call _invoke) == "missing"] call _check;
    ["shutdown", []] call _invoke;
    diag_log "[EDJ ARRAYS] COMPLETE - human listening and multiplayer remain separate acceptance";
    endMission "END1";
};
